-- Migration: Add client_request_id field to usage_logs and request_logs
-- Purpose: Add internal client_request_id for reliable correlation between tables
--
-- This migration adds a new client_request_id field (generated by gateway) and
-- makes the existing request_id field optional (since upstream APIs may not always
-- return x-request-id header).

BEGIN;

-- ============================================================================
-- Step 1: Add client_request_id to usage_logs
-- ============================================================================

-- Add the new client_request_id column (with temporary default)
ALTER TABLE usage_logs
  ADD COLUMN IF NOT EXISTS client_request_id VARCHAR(64);

-- Backfill: Use existing request_id as client_request_id for historical data
-- For rows with NULL request_id, generate a placeholder ID
UPDATE usage_logs
SET client_request_id = COALESCE(request_id, 'legacy-' || id::text)
WHERE client_request_id IS NULL;

-- Now make client_request_id NOT NULL
ALTER TABLE usage_logs
  ALTER COLUMN client_request_id SET NOT NULL;

-- Make request_id nullable (it comes from upstream and may be empty)
ALTER TABLE usage_logs
  ALTER COLUMN request_id DROP NOT NULL;

-- Remove OLD unique constraint on (request_id, api_key_id) - no longer needed
-- since request_id is now optional and client_request_id is the primary key
DROP INDEX IF EXISTS idx_usage_logs_request_id_api_key_unique;

-- Add index for client_request_id (primary correlation key)
CREATE INDEX IF NOT EXISTS idx_usage_logs_client_request_id
  ON usage_logs(client_request_id);

-- Add NEW UNIQUE constraint for (client_request_id, api_key_id) to support ON CONFLICT in repository
CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_logs_client_request_id_api_key_unique
  ON usage_logs(client_request_id, api_key_id);

-- Keep existing request_id index (for upstream tracing)
-- index already exists: idx_usage_logs_request_id


-- ============================================================================
-- Step 2: Add client_request_id to request_logs
-- ============================================================================

-- Add the new client_request_id column (with temporary default)
ALTER TABLE request_logs
  ADD COLUMN IF NOT EXISTS client_request_id VARCHAR(64);

-- Backfill: Use existing request_id as client_request_id for historical data
-- For rows with NULL request_id, generate a placeholder ID
UPDATE request_logs
SET client_request_id = COALESCE(request_id, 'legacy-' || id::text)
WHERE client_request_id IS NULL;

-- Now make client_request_id NOT NULL
ALTER TABLE request_logs
  ALTER COLUMN client_request_id SET NOT NULL;

-- Make request_id nullable (it comes from upstream and may be empty)
ALTER TABLE request_logs
  ALTER COLUMN request_id DROP NOT NULL;

-- Add index for client_request_id (primary correlation key)
CREATE INDEX IF NOT EXISTS idx_request_logs_client_request_id
  ON request_logs(client_request_id);

-- Add UNIQUE constraint for (client_request_id, api_key_id) to ensure data integrity
CREATE UNIQUE INDEX IF NOT EXISTS idx_request_logs_client_request_id_api_key_unique
  ON request_logs(client_request_id, api_key_id);

-- Keep existing request_id index (for upstream tracing)
-- index already exists: idx_request_logs_request_id


-- ============================================================================
-- Step 3: Add comments for documentation
-- ============================================================================

COMMENT ON COLUMN usage_logs.client_request_id IS
  '内部请求ID，由网关生成，用于关联 usage_logs 和 request_logs';

COMMENT ON COLUMN usage_logs.request_id IS
  '上游 API 返回的请求ID（x-request-id响应头，可能为空）';

COMMENT ON COLUMN request_logs.client_request_id IS
  '内部请求ID，由网关生成，用于关联 usage_logs 和 request_logs';

COMMENT ON COLUMN request_logs.request_id IS
  '上游 API 返回的请求ID（x-request-id响应头，可能为空）';

COMMIT;
