// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/requestlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RequestLogCreate is the builder for creating a RequestLog entity.
type RequestLogCreate struct {
	config
	mutation *RequestLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *RequestLogCreate) SetUserID(v int64) *RequestLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *RequestLogCreate) SetAPIKeyID(v int64) *RequestLogCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *RequestLogCreate) SetAccountID(v int64) *RequestLogCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetClientRequestID sets the "client_request_id" field.
func (_c *RequestLogCreate) SetClientRequestID(v string) *RequestLogCreate {
	_c.mutation.SetClientRequestID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *RequestLogCreate) SetRequestID(v string) *RequestLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableRequestID(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *RequestLogCreate) SetModel(v string) *RequestLogCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *RequestLogCreate) SetGroupID(v int64) *RequestLogCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableGroupID(v *int64) *RequestLogCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *RequestLogCreate) SetRequestBody(v string) *RequestLogCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetRequestMethod sets the "request_method" field.
func (_c *RequestLogCreate) SetRequestMethod(v string) *RequestLogCreate {
	_c.mutation.SetRequestMethod(v)
	return _c
}

// SetNillableRequestMethod sets the "request_method" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableRequestMethod(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetRequestMethod(*v)
	}
	return _c
}

// SetRequestPath sets the "request_path" field.
func (_c *RequestLogCreate) SetRequestPath(v string) *RequestLogCreate {
	_c.mutation.SetRequestPath(v)
	return _c
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableRequestPath(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetRequestPath(*v)
	}
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *RequestLogCreate) SetResponseBody(v string) *RequestLogCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableResponseBody(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetResponseBody(*v)
	}
	return _c
}

// SetResponseStatus sets the "response_status" field.
func (_c *RequestLogCreate) SetResponseStatus(v int) *RequestLogCreate {
	_c.mutation.SetResponseStatus(v)
	return _c
}

// SetNillableResponseStatus sets the "response_status" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableResponseStatus(v *int) *RequestLogCreate {
	if v != nil {
		_c.SetResponseStatus(*v)
	}
	return _c
}

// SetStream sets the "stream" field.
func (_c *RequestLogCreate) SetStream(v bool) *RequestLogCreate {
	_c.mutation.SetStream(v)
	return _c
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableStream(v *bool) *RequestLogCreate {
	if v != nil {
		_c.SetStream(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *RequestLogCreate) SetDurationMs(v int) *RequestLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableDurationMs(v *int) *RequestLogCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *RequestLogCreate) SetIPAddress(v string) *RequestLogCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableIPAddress(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *RequestLogCreate) SetUserAgent(v string) *RequestLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableUserAgent(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetIsError sets the "is_error" field.
func (_c *RequestLogCreate) SetIsError(v bool) *RequestLogCreate {
	_c.mutation.SetIsError(v)
	return _c
}

// SetNillableIsError sets the "is_error" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableIsError(v *bool) *RequestLogCreate {
	if v != nil {
		_c.SetIsError(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *RequestLogCreate) SetErrorMessage(v string) *RequestLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableErrorMessage(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetErrorType sets the "error_type" field.
func (_c *RequestLogCreate) SetErrorType(v string) *RequestLogCreate {
	_c.mutation.SetErrorType(v)
	return _c
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableErrorType(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetErrorType(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestLogCreate) SetCreatedAt(v time.Time) *RequestLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableCreatedAt(v *time.Time) *RequestLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RequestLogCreate) SetUser(v *User) *RequestLogCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *RequestLogCreate) SetAPIKey(v *APIKey) *RequestLogCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *RequestLogCreate) SetAccount(v *Account) *RequestLogCreate {
	return _c.SetAccountID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *RequestLogCreate) SetGroup(v *Group) *RequestLogCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the RequestLogMutation object of the builder.
func (_c *RequestLogCreate) Mutation() *RequestLogMutation {
	return _c.mutation
}

// Save creates the RequestLog in the database.
func (_c *RequestLogCreate) Save(ctx context.Context) (*RequestLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestLogCreate) SaveX(ctx context.Context) *RequestLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestLogCreate) defaults() {
	if _, ok := _c.mutation.RequestMethod(); !ok {
		v := requestlog.DefaultRequestMethod
		_c.mutation.SetRequestMethod(v)
	}
	if _, ok := _c.mutation.RequestPath(); !ok {
		v := requestlog.DefaultRequestPath
		_c.mutation.SetRequestPath(v)
	}
	if _, ok := _c.mutation.ResponseStatus(); !ok {
		v := requestlog.DefaultResponseStatus
		_c.mutation.SetResponseStatus(v)
	}
	if _, ok := _c.mutation.Stream(); !ok {
		v := requestlog.DefaultStream
		_c.mutation.SetStream(v)
	}
	if _, ok := _c.mutation.IsError(); !ok {
		v := requestlog.DefaultIsError
		_c.mutation.SetIsError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestLogCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RequestLog.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "RequestLog.api_key_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "RequestLog.account_id"`)}
	}
	if _, ok := _c.mutation.ClientRequestID(); !ok {
		return &ValidationError{Name: "client_request_id", err: errors.New(`ent: missing required field "RequestLog.client_request_id"`)}
	}
	if v, ok := _c.mutation.ClientRequestID(); ok {
		if err := requestlog.ClientRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "client_request_id", err: fmt.Errorf(`ent: validator failed for field "RequestLog.client_request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := requestlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "RequestLog.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := requestlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestLog.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestBody(); !ok {
		return &ValidationError{Name: "request_body", err: errors.New(`ent: missing required field "RequestLog.request_body"`)}
	}
	if v, ok := _c.mutation.RequestBody(); ok {
		if err := requestlog.RequestBodyValidator(v); err != nil {
			return &ValidationError{Name: "request_body", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestMethod(); !ok {
		return &ValidationError{Name: "request_method", err: errors.New(`ent: missing required field "RequestLog.request_method"`)}
	}
	if v, ok := _c.mutation.RequestMethod(); ok {
		if err := requestlog.RequestMethodValidator(v); err != nil {
			return &ValidationError{Name: "request_method", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestPath(); !ok {
		return &ValidationError{Name: "request_path", err: errors.New(`ent: missing required field "RequestLog.request_path"`)}
	}
	if v, ok := _c.mutation.RequestPath(); ok {
		if err := requestlog.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResponseStatus(); !ok {
		return &ValidationError{Name: "response_status", err: errors.New(`ent: missing required field "RequestLog.response_status"`)}
	}
	if _, ok := _c.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "RequestLog.stream"`)}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := requestlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RequestLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := requestlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "RequestLog.user_agent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsError(); !ok {
		return &ValidationError{Name: "is_error", err: errors.New(`ent: missing required field "RequestLog.is_error"`)}
	}
	if v, ok := _c.mutation.ErrorType(); ok {
		if err := requestlog.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "RequestLog.error_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestLog.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RequestLog.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "RequestLog.api_key"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "RequestLog.account"`)}
	}
	return nil
}

func (_c *RequestLogCreate) sqlSave(ctx context.Context) (*RequestLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestLogCreate) createSpec() (*RequestLog, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestlog.Table, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ClientRequestID(); ok {
		_spec.SetField(requestlog.FieldClientRequestID, field.TypeString, value)
		_node.ClientRequestID = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(requestlog.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(requestlog.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(requestlog.FieldRequestBody, field.TypeString, value)
		_node.RequestBody = value
	}
	if value, ok := _c.mutation.RequestMethod(); ok {
		_spec.SetField(requestlog.FieldRequestMethod, field.TypeString, value)
		_node.RequestMethod = value
	}
	if value, ok := _c.mutation.RequestPath(); ok {
		_spec.SetField(requestlog.FieldRequestPath, field.TypeString, value)
		_node.RequestPath = value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(requestlog.FieldResponseBody, field.TypeString, value)
		_node.ResponseBody = &value
	}
	if value, ok := _c.mutation.ResponseStatus(); ok {
		_spec.SetField(requestlog.FieldResponseStatus, field.TypeInt, value)
		_node.ResponseStatus = value
	}
	if value, ok := _c.mutation.Stream(); ok {
		_spec.SetField(requestlog.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(requestlog.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(requestlog.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = &value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(requestlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.IsError(); ok {
		_spec.SetField(requestlog.FieldIsError, field.TypeBool, value)
		_node.IsError = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(requestlog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.ErrorType(); ok {
		_spec.SetField(requestlog.FieldErrorType, field.TypeString, value)
		_node.ErrorType = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.UserTable,
			Columns: []string{requestlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.APIKeyTable,
			Columns: []string{requestlog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.AccountTable,
			Columns: []string{requestlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.GroupTable,
			Columns: []string{requestlog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestLog.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestLogCreate) OnConflict(opts ...sql.ConflictOption) *RequestLogUpsertOne {
	_c.conflict = opts
	return &RequestLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestLogCreate) OnConflictColumns(columns ...string) *RequestLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestLogUpsertOne{
		create: _c,
	}
}

type (
	// RequestLogUpsertOne is the builder for "upsert"-ing
	//  one RequestLog node.
	RequestLogUpsertOne struct {
		create *RequestLogCreate
	}

	// RequestLogUpsert is the "OnConflict" setter.
	RequestLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *RequestLogUpsert) SetUserID(v int64) *RequestLogUpsert {
	u.Set(requestlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateUserID() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestLogUpsert) SetAPIKeyID(v int64) *RequestLogUpsert {
	u.Set(requestlog.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateAPIKeyID() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldAPIKeyID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *RequestLogUpsert) SetAccountID(v int64) *RequestLogUpsert {
	u.Set(requestlog.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateAccountID() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldAccountID)
	return u
}

// SetClientRequestID sets the "client_request_id" field.
func (u *RequestLogUpsert) SetClientRequestID(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldClientRequestID, v)
	return u
}

// UpdateClientRequestID sets the "client_request_id" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateClientRequestID() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldClientRequestID)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *RequestLogUpsert) SetRequestID(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateRequestID() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RequestLogUpsert) ClearRequestID() *RequestLogUpsert {
	u.SetNull(requestlog.FieldRequestID)
	return u
}

// SetModel sets the "model" field.
func (u *RequestLogUpsert) SetModel(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateModel() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldModel)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *RequestLogUpsert) SetGroupID(v int64) *RequestLogUpsert {
	u.Set(requestlog.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateGroupID() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RequestLogUpsert) ClearGroupID() *RequestLogUpsert {
	u.SetNull(requestlog.FieldGroupID)
	return u
}

// SetRequestBody sets the "request_body" field.
func (u *RequestLogUpsert) SetRequestBody(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldRequestBody, v)
	return u
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateRequestBody() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldRequestBody)
	return u
}

// SetRequestMethod sets the "request_method" field.
func (u *RequestLogUpsert) SetRequestMethod(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldRequestMethod, v)
	return u
}

// UpdateRequestMethod sets the "request_method" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateRequestMethod() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldRequestMethod)
	return u
}

// SetRequestPath sets the "request_path" field.
func (u *RequestLogUpsert) SetRequestPath(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldRequestPath, v)
	return u
}

// UpdateRequestPath sets the "request_path" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateRequestPath() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldRequestPath)
	return u
}

// SetResponseBody sets the "response_body" field.
func (u *RequestLogUpsert) SetResponseBody(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldResponseBody, v)
	return u
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateResponseBody() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldResponseBody)
	return u
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *RequestLogUpsert) ClearResponseBody() *RequestLogUpsert {
	u.SetNull(requestlog.FieldResponseBody)
	return u
}

// SetResponseStatus sets the "response_status" field.
func (u *RequestLogUpsert) SetResponseStatus(v int) *RequestLogUpsert {
	u.Set(requestlog.FieldResponseStatus, v)
	return u
}

// UpdateResponseStatus sets the "response_status" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateResponseStatus() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldResponseStatus)
	return u
}

// AddResponseStatus adds v to the "response_status" field.
func (u *RequestLogUpsert) AddResponseStatus(v int) *RequestLogUpsert {
	u.Add(requestlog.FieldResponseStatus, v)
	return u
}

// SetStream sets the "stream" field.
func (u *RequestLogUpsert) SetStream(v bool) *RequestLogUpsert {
	u.Set(requestlog.FieldStream, v)
	return u
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateStream() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldStream)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestLogUpsert) SetDurationMs(v int) *RequestLogUpsert {
	u.Set(requestlog.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateDurationMs() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestLogUpsert) AddDurationMs(v int) *RequestLogUpsert {
	u.Add(requestlog.FieldDurationMs, v)
	return u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestLogUpsert) ClearDurationMs() *RequestLogUpsert {
	u.SetNull(requestlog.FieldDurationMs)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *RequestLogUpsert) SetIPAddress(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateIPAddress() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldIPAddress)
	return u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *RequestLogUpsert) ClearIPAddress() *RequestLogUpsert {
	u.SetNull(requestlog.FieldIPAddress)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *RequestLogUpsert) SetUserAgent(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateUserAgent() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *RequestLogUpsert) ClearUserAgent() *RequestLogUpsert {
	u.SetNull(requestlog.FieldUserAgent)
	return u
}

// SetIsError sets the "is_error" field.
func (u *RequestLogUpsert) SetIsError(v bool) *RequestLogUpsert {
	u.Set(requestlog.FieldIsError, v)
	return u
}

// UpdateIsError sets the "is_error" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateIsError() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldIsError)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestLogUpsert) SetErrorMessage(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateErrorMessage() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RequestLogUpsert) ClearErrorMessage() *RequestLogUpsert {
	u.SetNull(requestlog.FieldErrorMessage)
	return u
}

// SetErrorType sets the "error_type" field.
func (u *RequestLogUpsert) SetErrorType(v string) *RequestLogUpsert {
	u.Set(requestlog.FieldErrorType, v)
	return u
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *RequestLogUpsert) UpdateErrorType() *RequestLogUpsert {
	u.SetExcluded(requestlog.FieldErrorType)
	return u
}

// ClearErrorType clears the value of the "error_type" field.
func (u *RequestLogUpsert) ClearErrorType() *RequestLogUpsert {
	u.SetNull(requestlog.FieldErrorType)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestLogUpsertOne) UpdateNewValues() *RequestLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(requestlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestLogUpsertOne) Ignore() *RequestLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestLogUpsertOne) DoNothing() *RequestLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestLogCreate.OnConflict
// documentation for more info.
func (u *RequestLogUpsertOne) Update(set func(*RequestLogUpsert)) *RequestLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *RequestLogUpsertOne) SetUserID(v int64) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateUserID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestLogUpsertOne) SetAPIKeyID(v int64) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateAPIKeyID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *RequestLogUpsertOne) SetAccountID(v int64) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateAccountID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateAccountID()
	})
}

// SetClientRequestID sets the "client_request_id" field.
func (u *RequestLogUpsertOne) SetClientRequestID(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetClientRequestID(v)
	})
}

// UpdateClientRequestID sets the "client_request_id" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateClientRequestID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateClientRequestID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *RequestLogUpsertOne) SetRequestID(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateRequestID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RequestLogUpsertOne) ClearRequestID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearRequestID()
	})
}

// SetModel sets the "model" field.
func (u *RequestLogUpsertOne) SetModel(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateModel() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateModel()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RequestLogUpsertOne) SetGroupID(v int64) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateGroupID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RequestLogUpsertOne) ClearGroupID() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearGroupID()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *RequestLogUpsertOne) SetRequestBody(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateRequestBody() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateRequestBody()
	})
}

// SetRequestMethod sets the "request_method" field.
func (u *RequestLogUpsertOne) SetRequestMethod(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetRequestMethod(v)
	})
}

// UpdateRequestMethod sets the "request_method" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateRequestMethod() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateRequestMethod()
	})
}

// SetRequestPath sets the "request_path" field.
func (u *RequestLogUpsertOne) SetRequestPath(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetRequestPath(v)
	})
}

// UpdateRequestPath sets the "request_path" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateRequestPath() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateRequestPath()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *RequestLogUpsertOne) SetResponseBody(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateResponseBody() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *RequestLogUpsertOne) ClearResponseBody() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearResponseBody()
	})
}

// SetResponseStatus sets the "response_status" field.
func (u *RequestLogUpsertOne) SetResponseStatus(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetResponseStatus(v)
	})
}

// AddResponseStatus adds v to the "response_status" field.
func (u *RequestLogUpsertOne) AddResponseStatus(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddResponseStatus(v)
	})
}

// UpdateResponseStatus sets the "response_status" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateResponseStatus() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateResponseStatus()
	})
}

// SetStream sets the "stream" field.
func (u *RequestLogUpsertOne) SetStream(v bool) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateStream() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateStream()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestLogUpsertOne) SetDurationMs(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestLogUpsertOne) AddDurationMs(v int) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateDurationMs() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestLogUpsertOne) ClearDurationMs() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearDurationMs()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *RequestLogUpsertOne) SetIPAddress(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateIPAddress() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *RequestLogUpsertOne) ClearIPAddress() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearIPAddress()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *RequestLogUpsertOne) SetUserAgent(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateUserAgent() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *RequestLogUpsertOne) ClearUserAgent() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetIsError sets the "is_error" field.
func (u *RequestLogUpsertOne) SetIsError(v bool) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetIsError(v)
	})
}

// UpdateIsError sets the "is_error" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateIsError() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateIsError()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestLogUpsertOne) SetErrorMessage(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateErrorMessage() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RequestLogUpsertOne) ClearErrorMessage() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearErrorMessage()
	})
}

// SetErrorType sets the "error_type" field.
func (u *RequestLogUpsertOne) SetErrorType(v string) *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetErrorType(v)
	})
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *RequestLogUpsertOne) UpdateErrorType() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateErrorType()
	})
}

// ClearErrorType clears the value of the "error_type" field.
func (u *RequestLogUpsertOne) ClearErrorType() *RequestLogUpsertOne {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearErrorType()
	})
}

// Exec executes the query.
func (u *RequestLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestLogCreateBulk is the builder for creating many RequestLog entities in bulk.
type RequestLogCreateBulk struct {
	config
	err      error
	builders []*RequestLogCreate
	conflict []sql.ConflictOption
}

// Save creates the RequestLog entities in the database.
func (_c *RequestLogCreateBulk) Save(ctx context.Context) ([]*RequestLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestLogCreateBulk) SaveX(ctx context.Context) []*RequestLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestLogUpsertBulk {
	_c.conflict = opts
	return &RequestLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestLogCreateBulk) OnConflictColumns(columns ...string) *RequestLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestLogUpsertBulk{
		create: _c,
	}
}

// RequestLogUpsertBulk is the builder for "upsert"-ing
// a bulk of RequestLog nodes.
type RequestLogUpsertBulk struct {
	create *RequestLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestLogUpsertBulk) UpdateNewValues() *RequestLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(requestlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestLogUpsertBulk) Ignore() *RequestLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestLogUpsertBulk) DoNothing() *RequestLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestLogCreateBulk.OnConflict
// documentation for more info.
func (u *RequestLogUpsertBulk) Update(set func(*RequestLogUpsert)) *RequestLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *RequestLogUpsertBulk) SetUserID(v int64) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateUserID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *RequestLogUpsertBulk) SetAPIKeyID(v int64) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateAPIKeyID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *RequestLogUpsertBulk) SetAccountID(v int64) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateAccountID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateAccountID()
	})
}

// SetClientRequestID sets the "client_request_id" field.
func (u *RequestLogUpsertBulk) SetClientRequestID(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetClientRequestID(v)
	})
}

// UpdateClientRequestID sets the "client_request_id" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateClientRequestID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateClientRequestID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *RequestLogUpsertBulk) SetRequestID(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateRequestID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *RequestLogUpsertBulk) ClearRequestID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearRequestID()
	})
}

// SetModel sets the "model" field.
func (u *RequestLogUpsertBulk) SetModel(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateModel() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateModel()
	})
}

// SetGroupID sets the "group_id" field.
func (u *RequestLogUpsertBulk) SetGroupID(v int64) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateGroupID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *RequestLogUpsertBulk) ClearGroupID() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearGroupID()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *RequestLogUpsertBulk) SetRequestBody(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateRequestBody() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateRequestBody()
	})
}

// SetRequestMethod sets the "request_method" field.
func (u *RequestLogUpsertBulk) SetRequestMethod(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetRequestMethod(v)
	})
}

// UpdateRequestMethod sets the "request_method" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateRequestMethod() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateRequestMethod()
	})
}

// SetRequestPath sets the "request_path" field.
func (u *RequestLogUpsertBulk) SetRequestPath(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetRequestPath(v)
	})
}

// UpdateRequestPath sets the "request_path" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateRequestPath() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateRequestPath()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *RequestLogUpsertBulk) SetResponseBody(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateResponseBody() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *RequestLogUpsertBulk) ClearResponseBody() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearResponseBody()
	})
}

// SetResponseStatus sets the "response_status" field.
func (u *RequestLogUpsertBulk) SetResponseStatus(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetResponseStatus(v)
	})
}

// AddResponseStatus adds v to the "response_status" field.
func (u *RequestLogUpsertBulk) AddResponseStatus(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddResponseStatus(v)
	})
}

// UpdateResponseStatus sets the "response_status" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateResponseStatus() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateResponseStatus()
	})
}

// SetStream sets the "stream" field.
func (u *RequestLogUpsertBulk) SetStream(v bool) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateStream() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateStream()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *RequestLogUpsertBulk) SetDurationMs(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *RequestLogUpsertBulk) AddDurationMs(v int) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateDurationMs() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *RequestLogUpsertBulk) ClearDurationMs() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearDurationMs()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *RequestLogUpsertBulk) SetIPAddress(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateIPAddress() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *RequestLogUpsertBulk) ClearIPAddress() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearIPAddress()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *RequestLogUpsertBulk) SetUserAgent(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateUserAgent() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *RequestLogUpsertBulk) ClearUserAgent() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetIsError sets the "is_error" field.
func (u *RequestLogUpsertBulk) SetIsError(v bool) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetIsError(v)
	})
}

// UpdateIsError sets the "is_error" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateIsError() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateIsError()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *RequestLogUpsertBulk) SetErrorMessage(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateErrorMessage() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *RequestLogUpsertBulk) ClearErrorMessage() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearErrorMessage()
	})
}

// SetErrorType sets the "error_type" field.
func (u *RequestLogUpsertBulk) SetErrorType(v string) *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.SetErrorType(v)
	})
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *RequestLogUpsertBulk) UpdateErrorType() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.UpdateErrorType()
	})
}

// ClearErrorType clears the value of the "error_type" field.
func (u *RequestLogUpsertBulk) ClearErrorType() *RequestLogUpsertBulk {
	return u.Update(func(s *RequestLogUpsert) {
		s.ClearErrorType()
	})
}

// Exec executes the query.
func (u *RequestLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
