// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/requestlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RequestLogUpdate is the builder for updating RequestLog entities.
type RequestLogUpdate struct {
	config
	hooks    []Hook
	mutation *RequestLogMutation
}

// Where appends a list predicates to the RequestLogUpdate builder.
func (_u *RequestLogUpdate) Where(ps ...predicate.RequestLog) *RequestLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RequestLogUpdate) SetUserID(v int64) *RequestLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableUserID(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RequestLogUpdate) SetAPIKeyID(v int64) *RequestLogUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableAPIKeyID(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *RequestLogUpdate) SetAccountID(v int64) *RequestLogUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableAccountID(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetClientRequestID sets the "client_request_id" field.
func (_u *RequestLogUpdate) SetClientRequestID(v string) *RequestLogUpdate {
	_u.mutation.SetClientRequestID(v)
	return _u
}

// SetNillableClientRequestID sets the "client_request_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableClientRequestID(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetClientRequestID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RequestLogUpdate) SetRequestID(v string) *RequestLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableRequestID(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RequestLogUpdate) ClearRequestID() *RequestLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetModel sets the "model" field.
func (_u *RequestLogUpdate) SetModel(v string) *RequestLogUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableModel(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RequestLogUpdate) SetGroupID(v int64) *RequestLogUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableGroupID(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RequestLogUpdate) ClearGroupID() *RequestLogUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *RequestLogUpdate) SetRequestBody(v string) *RequestLogUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableRequestBody(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// SetRequestMethod sets the "request_method" field.
func (_u *RequestLogUpdate) SetRequestMethod(v string) *RequestLogUpdate {
	_u.mutation.SetRequestMethod(v)
	return _u
}

// SetNillableRequestMethod sets the "request_method" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableRequestMethod(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetRequestMethod(*v)
	}
	return _u
}

// SetRequestPath sets the "request_path" field.
func (_u *RequestLogUpdate) SetRequestPath(v string) *RequestLogUpdate {
	_u.mutation.SetRequestPath(v)
	return _u
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableRequestPath(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetRequestPath(*v)
	}
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestLogUpdate) SetResponseBody(v string) *RequestLogUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableResponseBody(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RequestLogUpdate) ClearResponseBody() *RequestLogUpdate {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseStatus sets the "response_status" field.
func (_u *RequestLogUpdate) SetResponseStatus(v int) *RequestLogUpdate {
	_u.mutation.ResetResponseStatus()
	_u.mutation.SetResponseStatus(v)
	return _u
}

// SetNillableResponseStatus sets the "response_status" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableResponseStatus(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetResponseStatus(*v)
	}
	return _u
}

// AddResponseStatus adds value to the "response_status" field.
func (_u *RequestLogUpdate) AddResponseStatus(v int) *RequestLogUpdate {
	_u.mutation.AddResponseStatus(v)
	return _u
}

// SetStream sets the "stream" field.
func (_u *RequestLogUpdate) SetStream(v bool) *RequestLogUpdate {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableStream(v *bool) *RequestLogUpdate {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestLogUpdate) SetDurationMs(v int) *RequestLogUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableDurationMs(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestLogUpdate) AddDurationMs(v int) *RequestLogUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *RequestLogUpdate) ClearDurationMs() *RequestLogUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RequestLogUpdate) SetIPAddress(v string) *RequestLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableIPAddress(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *RequestLogUpdate) ClearIPAddress() *RequestLogUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *RequestLogUpdate) SetUserAgent(v string) *RequestLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableUserAgent(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *RequestLogUpdate) ClearUserAgent() *RequestLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetIsError sets the "is_error" field.
func (_u *RequestLogUpdate) SetIsError(v bool) *RequestLogUpdate {
	_u.mutation.SetIsError(v)
	return _u
}

// SetNillableIsError sets the "is_error" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableIsError(v *bool) *RequestLogUpdate {
	if v != nil {
		_u.SetIsError(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestLogUpdate) SetErrorMessage(v string) *RequestLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableErrorMessage(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RequestLogUpdate) ClearErrorMessage() *RequestLogUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorType sets the "error_type" field.
func (_u *RequestLogUpdate) SetErrorType(v string) *RequestLogUpdate {
	_u.mutation.SetErrorType(v)
	return _u
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableErrorType(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetErrorType(*v)
	}
	return _u
}

// ClearErrorType clears the value of the "error_type" field.
func (_u *RequestLogUpdate) ClearErrorType() *RequestLogUpdate {
	_u.mutation.ClearErrorType()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RequestLogUpdate) SetUser(v *User) *RequestLogUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *RequestLogUpdate) SetAPIKey(v *APIKey) *RequestLogUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *RequestLogUpdate) SetAccount(v *Account) *RequestLogUpdate {
	return _u.SetAccountID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *RequestLogUpdate) SetGroup(v *Group) *RequestLogUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the RequestLogMutation object of the builder.
func (_u *RequestLogUpdate) Mutation() *RequestLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RequestLogUpdate) ClearUser() *RequestLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *RequestLogUpdate) ClearAPIKey() *RequestLogUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *RequestLogUpdate) ClearAccount() *RequestLogUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *RequestLogUpdate) ClearGroup() *RequestLogUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestLogUpdate) check() error {
	if v, ok := _u.mutation.ClientRequestID(); ok {
		if err := requestlog.ClientRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "client_request_id", err: fmt.Errorf(`ent: validator failed for field "RequestLog.client_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := requestlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := requestlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestBody(); ok {
		if err := requestlog.RequestBodyValidator(v); err != nil {
			return &ValidationError{Name: "request_body", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestMethod(); ok {
		if err := requestlog.RequestMethodValidator(v); err != nil {
			return &ValidationError{Name: "request_method", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestPath(); ok {
		if err := requestlog.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := requestlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RequestLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := requestlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "RequestLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorType(); ok {
		if err := requestlog.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "RequestLog.error_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLog.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLog.api_key"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLog.account"`)
	}
	return nil
}

func (_u *RequestLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientRequestID(); ok {
		_spec.SetField(requestlog.FieldClientRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(requestlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(requestlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(requestlog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(requestlog.FieldRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestMethod(); ok {
		_spec.SetField(requestlog.FieldRequestMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPath(); ok {
		_spec.SetField(requestlog.FieldRequestPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestlog.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(requestlog.FieldResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseStatus(); ok {
		_spec.SetField(requestlog.FieldResponseStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseStatus(); ok {
		_spec.AddField(requestlog.FieldResponseStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(requestlog.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestlog.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(requestlog.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(requestlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(requestlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(requestlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(requestlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.IsError(); ok {
		_spec.SetField(requestlog.FieldIsError, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(requestlog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorType(); ok {
		_spec.SetField(requestlog.FieldErrorType, field.TypeString, value)
	}
	if _u.mutation.ErrorTypeCleared() {
		_spec.ClearField(requestlog.FieldErrorType, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.UserTable,
			Columns: []string{requestlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.UserTable,
			Columns: []string{requestlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.APIKeyTable,
			Columns: []string{requestlog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.APIKeyTable,
			Columns: []string{requestlog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.AccountTable,
			Columns: []string{requestlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.AccountTable,
			Columns: []string{requestlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.GroupTable,
			Columns: []string{requestlog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.GroupTable,
			Columns: []string{requestlog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestLogUpdateOne is the builder for updating a single RequestLog entity.
type RequestLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestLogMutation
}

// SetUserID sets the "user_id" field.
func (_u *RequestLogUpdateOne) SetUserID(v int64) *RequestLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableUserID(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RequestLogUpdateOne) SetAPIKeyID(v int64) *RequestLogUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableAPIKeyID(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *RequestLogUpdateOne) SetAccountID(v int64) *RequestLogUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableAccountID(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetClientRequestID sets the "client_request_id" field.
func (_u *RequestLogUpdateOne) SetClientRequestID(v string) *RequestLogUpdateOne {
	_u.mutation.SetClientRequestID(v)
	return _u
}

// SetNillableClientRequestID sets the "client_request_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableClientRequestID(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetClientRequestID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RequestLogUpdateOne) SetRequestID(v string) *RequestLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableRequestID(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RequestLogUpdateOne) ClearRequestID() *RequestLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetModel sets the "model" field.
func (_u *RequestLogUpdateOne) SetModel(v string) *RequestLogUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableModel(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *RequestLogUpdateOne) SetGroupID(v int64) *RequestLogUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableGroupID(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *RequestLogUpdateOne) ClearGroupID() *RequestLogUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *RequestLogUpdateOne) SetRequestBody(v string) *RequestLogUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableRequestBody(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// SetRequestMethod sets the "request_method" field.
func (_u *RequestLogUpdateOne) SetRequestMethod(v string) *RequestLogUpdateOne {
	_u.mutation.SetRequestMethod(v)
	return _u
}

// SetNillableRequestMethod sets the "request_method" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableRequestMethod(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetRequestMethod(*v)
	}
	return _u
}

// SetRequestPath sets the "request_path" field.
func (_u *RequestLogUpdateOne) SetRequestPath(v string) *RequestLogUpdateOne {
	_u.mutation.SetRequestPath(v)
	return _u
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableRequestPath(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetRequestPath(*v)
	}
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestLogUpdateOne) SetResponseBody(v string) *RequestLogUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableResponseBody(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RequestLogUpdateOne) ClearResponseBody() *RequestLogUpdateOne {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseStatus sets the "response_status" field.
func (_u *RequestLogUpdateOne) SetResponseStatus(v int) *RequestLogUpdateOne {
	_u.mutation.ResetResponseStatus()
	_u.mutation.SetResponseStatus(v)
	return _u
}

// SetNillableResponseStatus sets the "response_status" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableResponseStatus(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetResponseStatus(*v)
	}
	return _u
}

// AddResponseStatus adds value to the "response_status" field.
func (_u *RequestLogUpdateOne) AddResponseStatus(v int) *RequestLogUpdateOne {
	_u.mutation.AddResponseStatus(v)
	return _u
}

// SetStream sets the "stream" field.
func (_u *RequestLogUpdateOne) SetStream(v bool) *RequestLogUpdateOne {
	_u.mutation.SetStream(v)
	return _u
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableStream(v *bool) *RequestLogUpdateOne {
	if v != nil {
		_u.SetStream(*v)
	}
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestLogUpdateOne) SetDurationMs(v int) *RequestLogUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableDurationMs(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestLogUpdateOne) AddDurationMs(v int) *RequestLogUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *RequestLogUpdateOne) ClearDurationMs() *RequestLogUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RequestLogUpdateOne) SetIPAddress(v string) *RequestLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableIPAddress(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *RequestLogUpdateOne) ClearIPAddress() *RequestLogUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *RequestLogUpdateOne) SetUserAgent(v string) *RequestLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableUserAgent(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *RequestLogUpdateOne) ClearUserAgent() *RequestLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetIsError sets the "is_error" field.
func (_u *RequestLogUpdateOne) SetIsError(v bool) *RequestLogUpdateOne {
	_u.mutation.SetIsError(v)
	return _u
}

// SetNillableIsError sets the "is_error" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableIsError(v *bool) *RequestLogUpdateOne {
	if v != nil {
		_u.SetIsError(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestLogUpdateOne) SetErrorMessage(v string) *RequestLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableErrorMessage(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RequestLogUpdateOne) ClearErrorMessage() *RequestLogUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetErrorType sets the "error_type" field.
func (_u *RequestLogUpdateOne) SetErrorType(v string) *RequestLogUpdateOne {
	_u.mutation.SetErrorType(v)
	return _u
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableErrorType(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetErrorType(*v)
	}
	return _u
}

// ClearErrorType clears the value of the "error_type" field.
func (_u *RequestLogUpdateOne) ClearErrorType() *RequestLogUpdateOne {
	_u.mutation.ClearErrorType()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RequestLogUpdateOne) SetUser(v *User) *RequestLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *RequestLogUpdateOne) SetAPIKey(v *APIKey) *RequestLogUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *RequestLogUpdateOne) SetAccount(v *Account) *RequestLogUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *RequestLogUpdateOne) SetGroup(v *Group) *RequestLogUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the RequestLogMutation object of the builder.
func (_u *RequestLogUpdateOne) Mutation() *RequestLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RequestLogUpdateOne) ClearUser() *RequestLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *RequestLogUpdateOne) ClearAPIKey() *RequestLogUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *RequestLogUpdateOne) ClearAccount() *RequestLogUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *RequestLogUpdateOne) ClearGroup() *RequestLogUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the RequestLogUpdate builder.
func (_u *RequestLogUpdateOne) Where(ps ...predicate.RequestLog) *RequestLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestLogUpdateOne) Select(field string, fields ...string) *RequestLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestLog entity.
func (_u *RequestLogUpdateOne) Save(ctx context.Context) (*RequestLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogUpdateOne) SaveX(ctx context.Context) *RequestLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestLogUpdateOne) check() error {
	if v, ok := _u.mutation.ClientRequestID(); ok {
		if err := requestlog.ClientRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "client_request_id", err: fmt.Errorf(`ent: validator failed for field "RequestLog.client_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := requestlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := requestlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "RequestLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestBody(); ok {
		if err := requestlog.RequestBodyValidator(v); err != nil {
			return &ValidationError{Name: "request_body", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestMethod(); ok {
		if err := requestlog.RequestMethodValidator(v); err != nil {
			return &ValidationError{Name: "request_method", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestPath(); ok {
		if err := requestlog.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "RequestLog.request_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := requestlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RequestLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := requestlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "RequestLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorType(); ok {
		if err := requestlog.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "RequestLog.error_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLog.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLog.api_key"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestLog.account"`)
	}
	return nil
}

func (_u *RequestLogUpdateOne) sqlSave(ctx context.Context) (_node *RequestLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestlog.FieldID)
		for _, f := range fields {
			if !requestlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientRequestID(); ok {
		_spec.SetField(requestlog.FieldClientRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(requestlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(requestlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(requestlog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(requestlog.FieldRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestMethod(); ok {
		_spec.SetField(requestlog.FieldRequestMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPath(); ok {
		_spec.SetField(requestlog.FieldRequestPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestlog.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(requestlog.FieldResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseStatus(); ok {
		_spec.SetField(requestlog.FieldResponseStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseStatus(); ok {
		_spec.AddField(requestlog.FieldResponseStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Stream(); ok {
		_spec.SetField(requestlog.FieldStream, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestlog.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(requestlog.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(requestlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(requestlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(requestlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(requestlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.IsError(); ok {
		_spec.SetField(requestlog.FieldIsError, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(requestlog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorType(); ok {
		_spec.SetField(requestlog.FieldErrorType, field.TypeString, value)
	}
	if _u.mutation.ErrorTypeCleared() {
		_spec.ClearField(requestlog.FieldErrorType, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.UserTable,
			Columns: []string{requestlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.UserTable,
			Columns: []string{requestlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.APIKeyTable,
			Columns: []string{requestlog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.APIKeyTable,
			Columns: []string{requestlog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.AccountTable,
			Columns: []string{requestlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.AccountTable,
			Columns: []string{requestlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.GroupTable,
			Columns: []string{requestlog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestlog.GroupTable,
			Columns: []string{requestlog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RequestLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
