// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/requestlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RequestLog is the model entity for the RequestLog schema.
type RequestLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// 请求唯一ID，与usage_logs表关联
	RequestID string `json:"request_id,omitempty"`
	// 模型名称
	Model string `json:"model,omitempty"`
	// 分组ID
	GroupID *int64 `json:"group_id,omitempty"`
	// 完整请求体JSON
	RequestBody string `json:"request_body,omitempty"`
	// HTTP方法
	RequestMethod string `json:"request_method,omitempty"`
	// 请求路径
	RequestPath string `json:"request_path,omitempty"`
	// 完整响应体JSON（非流式）或聚合内容（流式）
	ResponseBody *string `json:"response_body,omitempty"`
	// HTTP状态码
	ResponseStatus int `json:"response_status,omitempty"`
	// 是否流式响应
	Stream bool `json:"stream,omitempty"`
	// 请求耗时（毫秒）
	DurationMs *int `json:"duration_ms,omitempty"`
	// 客户端IP地址
	IPAddress *string `json:"ip_address,omitempty"`
	// User-Agent头信息
	UserAgent *string `json:"user_agent,omitempty"`
	// 是否错误请求
	IsError bool `json:"is_error,omitempty"`
	// 错误信息
	ErrorMessage *string `json:"error_message,omitempty"`
	// 错误类型
	ErrorType *string `json:"error_type,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RequestLogQuery when eager-loading is set.
	Edges        RequestLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RequestLogEdges holds the relations/edges for other nodes in the graph.
type RequestLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestLogEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestLogEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestLogEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestlog.FieldStream, requestlog.FieldIsError:
			values[i] = new(sql.NullBool)
		case requestlog.FieldID, requestlog.FieldUserID, requestlog.FieldAPIKeyID, requestlog.FieldAccountID, requestlog.FieldGroupID, requestlog.FieldResponseStatus, requestlog.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case requestlog.FieldRequestID, requestlog.FieldModel, requestlog.FieldRequestBody, requestlog.FieldRequestMethod, requestlog.FieldRequestPath, requestlog.FieldResponseBody, requestlog.FieldIPAddress, requestlog.FieldUserAgent, requestlog.FieldErrorMessage, requestlog.FieldErrorType:
			values[i] = new(sql.NullString)
		case requestlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestLog fields.
func (_m *RequestLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case requestlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case requestlog.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case requestlog.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case requestlog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case requestlog.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case requestlog.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case requestlog.FieldRequestBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value.Valid {
				_m.RequestBody = value.String
			}
		case requestlog.FieldRequestMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_method", values[i])
			} else if value.Valid {
				_m.RequestMethod = value.String
			}
		case requestlog.FieldRequestPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_path", values[i])
			} else if value.Valid {
				_m.RequestPath = value.String
			}
		case requestlog.FieldResponseBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value.Valid {
				_m.ResponseBody = new(string)
				*_m.ResponseBody = value.String
			}
		case requestlog.FieldResponseStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_status", values[i])
			} else if value.Valid {
				_m.ResponseStatus = int(value.Int64)
			}
		case requestlog.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				_m.Stream = value.Bool
			}
		case requestlog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int)
				*_m.DurationMs = int(value.Int64)
			}
		case requestlog.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = new(string)
				*_m.IPAddress = value.String
			}
		case requestlog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = new(string)
				*_m.UserAgent = value.String
			}
		case requestlog.FieldIsError:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_error", values[i])
			} else if value.Valid {
				_m.IsError = value.Bool
			}
		case requestlog.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case requestlog.FieldErrorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_type", values[i])
			} else if value.Valid {
				_m.ErrorType = new(string)
				*_m.ErrorType = value.String
			}
		case requestlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestLog.
// This includes values selected through modifiers, order, etc.
func (_m *RequestLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the RequestLog entity.
func (_m *RequestLog) QueryUser() *UserQuery {
	return NewRequestLogClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the RequestLog entity.
func (_m *RequestLog) QueryAPIKey() *APIKeyQuery {
	return NewRequestLogClient(_m.config).QueryAPIKey(_m)
}

// QueryAccount queries the "account" edge of the RequestLog entity.
func (_m *RequestLog) QueryAccount() *AccountQuery {
	return NewRequestLogClient(_m.config).QueryAccount(_m)
}

// QueryGroup queries the "group" edge of the RequestLog entity.
func (_m *RequestLog) QueryGroup() *GroupQuery {
	return NewRequestLogClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this RequestLog.
// Note that you need to call RequestLog.Unwrap() before calling this method if this RequestLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestLog) Update() *RequestLogUpdateOne {
	return NewRequestLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestLog) Unwrap() *RequestLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestLog) String() string {
	var builder strings.Builder
	builder.WriteString("RequestLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(_m.RequestBody)
	builder.WriteString(", ")
	builder.WriteString("request_method=")
	builder.WriteString(_m.RequestMethod)
	builder.WriteString(", ")
	builder.WriteString("request_path=")
	builder.WriteString(_m.RequestPath)
	builder.WriteString(", ")
	if v := _m.ResponseBody; v != nil {
		builder.WriteString("response_body=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("response_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseStatus))
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stream))
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IPAddress; v != nil {
		builder.WriteString("ip_address=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserAgent; v != nil {
		builder.WriteString("user_agent=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_error=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsError))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorType; v != nil {
		builder.WriteString("error_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RequestLogs is a parsable slice of RequestLog.
type RequestLogs []*RequestLog
